### ISSUE TITLE
The mod crashes server.

### ISSUE THREAD

**Issue by sjackser** [legobmw99/BetterThanMending#11]
[crash-2020-02-16_00.27.06-server.txt](https://github.com/legobmw99/BetterThanMending/files/4208735/crash-2020-02-16_00.27.06-server.txt)
Crash report here

**Comment by legobmw99** [comment]
Did the player on the server have the mod installed?

**Comment by sjackser** [comment]
> Did the player on the server have the mod installed?

No, is it required?

**Comment by legobmw99** [comment]
Yes. I'll look into making it serverside only - the Forge version works like that at the moment - but for now simply have your users install it

**Comment by sjackser** [comment]
> Yes. I'll look into making it serverside only - the Forge version works like that at the moment - but for now simply have your users install it

ah ok, thx
