### ISSUE TITLE
Doesn't seem to work as efficiently with Netherite Pickaxe with full enchants..

### ISSUE THREAD

**Issue by hauntingly** [legobmw99/BetterThanMending#13]
It'll take me a good minute for me to shift n' right-click for the pickaxe to get repaired. I don't know whether or not it's supposed to be like this but, I would love to see a fix for this. Thanks!

**Comment by legobmw99** [comment]
This is a result of how Netherite has more durability. 

See #12 for discussion of possibly making the mending faster
