### ISSUE TITLE
Forge 1.5.0 not working on server

### ISSUE THREAD

**Issue by PedoraTheXplora** [legobmw99/BetterThanMending#14]
I'm not able to get the most recent forge version to work on my server. It works fine in singleplayer (even with other mods), but if I load the server with just this mod (on both server and client) it does not work. The fabric version worked when I tested it, so it seems to be a forge specific problem. Any ideas? Note: I have posted the same issue on the Twitch page.

**Comment by legobmw99** [comment]
Can I get a forge version? 

Does both the server and the client have the mod, or just the server?

**Comment by PedoraTheXplora** [comment]
Forge 1.16.1 32.0.108. I tried both the client and server having the mod, and with just the server having the mod.

**Comment by PedoraTheXplora** [comment]
I think it might be a forge problem. Some other previously working mods I used on previous 1.16 versions of forge no longer work on my server.

**Comment by James103** [comment]
Did you try downgrading Forge to the latest recommended version?

**Comment by PedoraTheXplora** [comment]
Forge 32.0.108 was the latest version of 1.16.1 when I had the issue. I’ve since given up and am going to switch to fabric 1.16.2 anyways

**Comment by legobmw99** [comment]
Stale issue
