### ISSUE TITLE
Can't right click to mend

### ISSUE THREAD

**Issue by Laifsyn** [legobmw99/BetterThanMending#18]
Version 1.18.2. I would like to know if there's a like a way to find out what mod is disabling it, like log checking for something in specific or idk? Or does it not work for 1.18.2?

**Comment by legobmw99** [comment]
Are you using forge or fabric?

Do you have a list of other mods you're using?

**Comment by Laifsyn** [comment]
Fabric, this is my current list 
```
betterthanmending-1.3.0.jar
fabric-api-0.51.1+1.18.2.jar

```
removed batch by batch until I've reached here

**Comment by Laifsyn** [comment]
wait, give me 5 minutes. My brain must have been shut off during all this time

**Comment by Laifsyn** [comment]
Yeah. I was just dumb. Forgot the mending enchantment. Sincere apologies
almost one hour of my life spent mod hunting futilely
