### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Laifsyn** [legobmw99/BetterThanMending#19]
Can I Request for a config which would allow you how much xp is converted into durability? like x0.5 of vanilla's durability is restored when right clicking

**Comment by legobmw99** [comment]
It should be the same ratio that vanilla uses when doing normal mending. I haven't checked this in a bit but I would be surprised if it had changed

**Comment by Laifsyn** [comment]
more like, I would like to nerf this mod's mending xD

**Comment by legobmw99** [comment]
I do not plan on making it configurable
