### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TookUrSweetRoll** [legobmw99/BetterThanMending#2]
I'm looking for a mod that makes items with mending on them unbreakable. For instance, a pick at 1 durability does not work until repaired, but does not get destroyed.  Optimally I would like for it to be a part of this mod, but if you cannot do it or are not interested, I will try my luck on the forums. Thanks.

BTW...This mod is genius.

**Comment by legobmw99** [comment]
I will look into making this (probably as a second, separate mod?), but it will probably be at least a couple weeks before I have the time 
		
		

		
	




On Tue, Feb 27, 2018 at 5:29 PM -0500, "TookUrSweetRoll" <notifications@github.com> wrote:












I'm looking for a mod that makes items with mending on them unbreakable. For instance, a pick at 1 durability does not work until repaired, but does not get destroyed.  Optimally I would like for it to be a part of this mod, but if you cannot do it or are not interested, I will try my luck on the forums. Thanks.


BTW...This mod is genius.

**Comment by TookUrSweetRoll** [comment]
A separate mod would be okay. I have zero modding skills, so I will appreciate whatever you come up with.
