### ISSUE TITLE
[Question] Is this mod client-side or server-side? Or both?

### ISSUE THREAD

**Issue by ShockedCoder** [legobmw99/BetterThanMending#20]
Version: Forge 1.16.5

I went through both the code and the issues to figure out which side I need to install the mod on, but I couldn't figure it out.
So, I was wondering if I could ask about it.

**Comment by ShockedCoder** [comment]
Found this [line](https://github.com/legobmw99/BetterThanMending/blob/master/src/main/resources/META-INF/mods.toml#L40) right here, and figured it out.

**Comment by ShockedCoder** [comment]
You should fix the Modrinth page about this though.

**Comment by WardBrian** [comment]
I believe it is possible to install it only on the server, but I would recommend installing it on both sides to avoid any odd behavior.
