### ISSUE TITLE
[1.19] Forge 41.0.98 Crash

### ISSUE THREAD

**Issue by rootwalla** [legobmw99/BetterThanMending#22]
There were apparently some breaking changes in forge .94 and it seems Better than mending was affected.
Crashes on eating.

log appended.
[crash-2022-07-15_20.33.53-client.txt](https://github.com/legobmw99/BetterThanMending/files/9123206/crash-2022-07-15_20.33.53-client.txt)

**Comment by legobmw99** [comment]
Thanks for the report!

**Comment by legobmw99** [comment]
Resolved by a6f12f6
