### ISSUE TITLE
Compatibility with Mending Levels

### ISSUE THREAD

**Issue by Seltyk** [legobmw99/BetterThanMending#23]
The [Mending Levels](https://modrinth.com/mod/mendinglevels) mod gives Mending multiple levels, where higher levels correspond to more repair for the same XP. In my testing, this mod does not interact with Mending Levels at all. More specifically, using Better Than Mending to mend a gold shovel added 4 durability per right click at both level I and level V enchantments.

I was using BTM v1.3.0 and ML v1.0.1 on Minecraft 1.18.2 with [Quilt](https://quiltmc.org/) 0.17.2-beta.2

**Comment by legobmw99** [comment]
In 1.21 and future versions this is supported via the vanilla enchantment datapack features. I don't intend to support it for earlier versions
