### ISSUE TITLE
[FR] Use levels instead of XP

### ISSUE THREAD

**Issue by imaron85** [legobmw99/BetterThanMending#26]
Hi there. We are using this mod on a quite technical server, which means we have an abundance of experience. I think it would be a nice nerf, if there was a possibility/setting to have the mending consume based on levels rather than xp, thus making repairing at higher levels more expensive.
We are often at hundreds of levels where the xp consumption doesn't even make a dent in our level bar, which feels rather unfair..

**Comment by legobmw99** [comment]
I don't plan on making the mod configuable in this way
