### ISSUE TITLE
Compability With Other Mods Using UseItemCallback

### ISSUE THREAD

**Issue by Phoupraw** [legobmw99/BetterThanMending#27]
`UseItemCallback.EVENT` will cancel furthur callbacks when former callback doesn't return `pass`. Suggest use `Event#register(net.minecraft.util.Identifier, T)` instead of `Event#register(T)` to provide a way for other mods to adjust the callback order.

**Comment by legobmw99** [comment]
Never knew about this. Closed in af18d425df6d7d70d51462b943ac871f203bc500

Thanks
