### ISSUE TITLE
[Feature Request] Add configurable keybind

### ISSUE THREAD

**Issue by EnderGirl1500** [legobmw99/BetterThanMending#28]
I have Fabrication, which uses shift+right click on tools as well. If both actions can take place, Better than Mending wins, which is a bit frustrating if I don't want to repair my tool, and what I need to do is waste all my xp before using Fabrication's feature (which is swapping between fortune and silk touch).

It would be nice if there could be a configurable keybind to make both mods compatible.

Already asked the other mod's dev as well

**Comment by legobmw99** [comment]
I have been avoiding this for a technical reason. Better Than Mending doesn't strictly speaking use a keybind, it uses whether or not the player is sneaking. This is an important distinction that allows the mod to be server-only. 

A keybind would require additional client-server communication every use, and require the user to have the mod installed client side.

**Comment by EnderGirl1500** [comment]
Ok, don't worry then ^^ Fabrication's dev added it so no more issues :)
