### ISSUE TITLE
Suggestion/Conflict with With Sprinkles Mod

### ISSUE THREAD

**Issue by ExcitedName** [legobmw99/BetterThanMending#3]
The With Sprinkles mod comes with an enchantment called Multiple. It allows an item to be enchanted with multiple sets of enchantments. Shift+r-click is used to switch between sets. This combination results in items having to be fully repaired before being able to switch sets, defeating the purpose of your mod. Would it be possible to add a hotkey? I have also posted this suggestion/conflict on With Sprinkles GitHub.

**Comment by legobmw99** [comment]
I really want to avoid adding hotkeys to such a simple mod, modded minecraft has too many already

**Comment by ExcitedName** [comment]
I understand why you want to avoid the hotkey, I actually agree. I am still having this conflict however. My pick has three sets of enchantments on it. The same method is used to switch as is used to mend. So I have to med my pick every time I change sets. I would imagine the reason you made this mod was to be able to give control over when mending happened, to give control of when the xp is spent. Again this conflict directly undermines your mod. So I either deal with repairing my tools every time I switch sets or go without your or the other mod. I am not trying to be pushy or complain. I would also like to clarify that my request before was to have a config added to choose which method to use. Either way I appreciate your time on this.
