### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by cqm3ron** [legobmw99/BetterThanMending#32]
Title. Would be much appreciated :D

**Comment by legobmw99** [comment]
I haven't checked to make sure it doesn't already work (this mod is small enough that sometimes it does), but if not I'm hoping to update this weekend

**Comment by cqm3ron** [comment]
I just tried it, and I can confirm that it definitely does not work, at least the default version from Modrinth.

**Comment by legobmw99** [comment]
0063a8104cd1052e905a59cb9dd3a54b7a7c80b1
