### ISSUE TITLE
Feature - armor

### ISSUE THREAD

**Issue by sternschnaube** [legobmw99/BetterThanMending#33]
Do you think it's possible to shift+left click armor to repair them up?

**Comment by legobmw99** [comment]
You should still be able to shift-right-click armor. It won't equip if it can repair

**Comment by sternschnaube** [comment]
That's sadly not the case. It swaps just the armor.

**Comment by legobmw99** [comment]
Version information?

**Comment by sternschnaube** [comment]
Latest on 1.21.

**Comment by legobmw99** [comment]
Fabric? Forge? Neo? And any other mods involved?

**Comment by sternschnaube** [comment]
Fabric. Having a large mod list.

**Comment by legobmw99** [comment]
Can't reproduce with just fabric + fabric API + BTM, so it might be another mod on your list interfering

**Comment by sternschnaube** [comment]
Thanks for letting me know. Maybe I look deeper into this and letting you know which mod is conflicting there.

**Comment by LordEnder-Kitty** [comment]
You can still repair equipables. The thing is that when you shift click it though, it goes out of sync on the client and so your client thinks that you equipped it even though its still in your hand. If you just have another item (e.i. a chestplate and an elytra) that you can swap with, it should work, albeit very scuffed. (all my experience with this though is with it on the server and not on the client, so it might be different on singleplayer)
