### ISSUE TITLE
Doesn't work if xp is given via command

### ISSUE THREAD

**Issue by ExcitedName** [legobmw99/BetterThanMending#6]
I noticed that the mod works just fine when using xp that I acquire through game play or an Bottle o' Enchanting, basically any orbs I directly pick up. I made a function command project that stores my xp and any xp retrieved from the command, xp 1L @p, does not work. I added GlobalXP mod to help troubleshoot and it seems to have the same issue with acquired vs given xp. I am wondering if the previously reported issues are with mods that give/take xp in a way that causes this.

**Comment by ExcitedName** [comment]
Thank you for the fix. I appreciate it.

**Comment by legobmw99** [comment]
Thanks for reporting. I was testing with bottles of experience, not the xp command, so I probably would not have found the issue. It seems that it is actually be a vanilla bug, but it was easy enough to get around

**Comment by ExcitedName** [comment]
I'm glad I could help. I find it funny that I, too, found a work around on my end. I just changed the system to use glass bottles to bottles of xp and vice versa. I was planning on adding an xp rod to be able to store xp via scoreboard, now I can make that happen and be compatible with this fix. Thanks again for your time on this.  :-)
