### ISSUE TITLE
Vanilla players crash server

### ISSUE THREAD

**Issue by tal985** [legobmw99/BetterThanMending#7]
On "MC 1.14 FABRIC - BetterThanMending 1.0.0", if a purely vanilla player tries to shift+right click to repair a tool that has mending on it, the server will crash.

**Comment by legobmw99** [comment]
Do you have a stacktrace or crash log? This sounds like simply unsupported behavior but if it's an obvious bug I'll look into it

**Comment by tal985** [comment]
This should be the server's crash [log.](https://pastebin.com/ANa3hX2S)

**Comment by legobmw99** [comment]
Yeah, this appears to be outside the area I can support. If you're using the mod on a server, so should all your players
