### ISSUE TITLE
[1.14]4 Sided code causing server crash

### ISSUE THREAD

**Issue by itsmeow** [legobmw99/BetterThanMending#8]
There's a bunch of clientside stuff being loaded including CPlayerTryUseItemPacket and Minecraft that happens when the player rightclick/shifts a mending item.
[2019-09-07-3.log](https://github.com/legobmw99/BetterThanMending/files/3586701/2019-09-07-3.log)

**Comment by legobmw99** [comment]
Does the same error occur when WorldEdit is not installed?

**Comment by itsmeow** [comment]
Huh. Just took a look at your code, that's really odd. WE is probably messing with something? I have no idea, your code is completely serverside. welp...

**Comment by itsmeow** [comment]
Nevermind, you're using Network.sendToServer on the server! Duh! Don't do that, lol
