### ISSUE TITLE
Doesn't work with fishing rod

### ISSUE THREAD

**Issue by SirWindfield** [legobmw99/BetterThanMending#9]
Holding shift and right clicking with a fishing rod in hand will throw the bobber instead of repairing the rod

**Comment by legobmw99** [comment]
Can I get some more details? What version is this, and are you a Forge or Fabric user?

Also, just to check, the rod has mending on it right?

**Comment by SirWindfield** [comment]
Kind of embarrassing... I didn't even notice that there were two versions for Forge and Fabric. I just installed the wrong one haha >.>

Sorry for the inconvenience

**Comment by legobmw99** [comment]
Happens more often than you’d think

Hope you enjoy the mod!
